version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:813048754227:task-definition/vdcs-collection-service-task:5"
        LoadBalancerInfo:
          ContainerName: "vdcs-collection-service-container"
          ContainerPort: "7100"
        PlatformVersion: "LATEST"